### ISSUE TITLE
Widget doesn't get removed on app uninstall

### ISSUE THREAD

**Issue by mhettig** [martinhellwig/DatapassWidget#1]
Currently the widget stays on the homescreen of the user if he/she uninstalls the app.

Whats even worth: Instead of the (old) widget the user sees a "Problem loading widget" placeholder.

**Comment by SEQUOiA87** [comment]
Dear reporter, please specify your environment :P

Issue not reproducible on Pixel XL with Android 7.1.1.

**Comment by mhettig** [comment]
:P
Huawei P9 - Android 6.0
See screenshot for details:

![screenshot_2016-12-28-16-36-44](https://cloud.githubusercontent.com/assets/2598617/21525289/a634f5bc-cd1c-11e6-83f9-cfd0aaed58b3.png)

**Comment by martinhellwig** [comment]
On my phone (OnePlus Two with Android 7.1) this bug also does not apper. I've tested with Now-Launcher and Pixel-Launcher. @mhettig: Please try this with the Google Now Launcher (simply download on Play Store and say active via settings)

**Comment by mhettig** [comment]
Okay, here are my investigations so far:

- I just updated my phone to the latest Android version provided by Huawei (7.0 - EMUI 5.0 Launcher). After uninstallation the widget also remains on the homescreen. In contrast to the previous version of EMUI no "problem loading widget" placeholder is shown but the widget as usaul which is of course no longer clickable. Strange behavior. You have to remove the widget manually.

- Also I checked the Google Now Launcher (which seems pretty outdated - 2015-11-02 according to the Play Store) and with that everything works like charm.

- In addition I installed our widget on my old Samsung Galaxy S3 with an inofficial Cyanogenmod 12.1 port and even there the widget gets removed on app uninstall.

So it seems to be a problem with Huawei's current launcher. I'll close this issue for now.
