### ISSUE TITLE
Delete references to old (inactive) widgets

### ISSUE THREAD

**Issue by martinhellwig** [martinhellwig/DatapassWidget#11]
In the preferences all widget-ids of all widgets are saved to trigger updates on NetworkChange.

Maybe we can maintain the list. So if there are 3 entries in the widgetId-list, but only 2 widgets are actively put on the users screen, delete the entry of the third one. We could do this with a timeToLive-variable. Each id only lives maximum e.g. 10 days without change. Normally each active widget gets updated every 6 hours (atm), so we could track, which of the widgetIds are really needed

**Comment by SEQUOiA87** [comment]
Isn't there a call method we can override with our AppWidgetProvider which informs about (a) deleted wigdet(s)?

**Comment by SEQUOiA87** [comment]
Here: https://developer.android.com/reference/android/appwidget/AppWidgetProvider.html#onDeleted(android.content.Context, int[])

We also should override the onRestore() method and handle the case of backup restore properly.

**Comment by martinhellwig** [comment]
Closed by ece4463. onRestored has now UseCase atm. But a comment reminds us to use it in the future, if we have widget-specific settings, which we could restore
