### ISSUE TITLE
Handle dual sim phones

### ISSUE THREAD

**Issue by mhettig** [martinhellwig/DatapassWidget#12]
As already introduced by @martinhellwig in 196c0eb we should consider the possibility that a user may use a dual sim mobile phone. In addition to the mentioned commit (where only the first supported carrier is selected) there is a chance that the user got two supported carriers. In this case the usage data of the second sim card could never be analyzed.

I got the following ideas in my mind, feel free to add different ones!
- Some kind of selection dialog when putting the widget on the homescreen allowing the user to select from a list of used && supported carriers. Of course only shown if there is more than one carrier available on the phone.
- Automatically (if possible) select for the first widget on the homescreen the first supported carrier and for the second widget the second supported carrier.
- Nevertheless user feedback would be needed, e.g. showing the carrier's name in the widget if there are two widgets on the homescreen so the user can distinguish between both.

**Comment by martinhellwig** [comment]
Closed with commit 8382187

If a user has Lollilop or up, he will be asked via a dialogue, which carrier the widget should be used for. This widget only appears, if there is more than 1 supported carrier. To get all carrier names, we need to request the "telephony"-permission.
