### ISSUE TITLE
App stucked while animation is going on

### ISSUE THREAD

**Issue by martinhellwig** [martinhellwig/DatapassWidget#17]
Sometimes all placed widgets are stuck while their animation was ongoing. 

As a user you can't do anything now. Click-Listener is not set. You only can delete the widget and place a new one. Probably a small bug in the animation process @mhettig?

**Comment by martinhellwig** [comment]
Maybe fixed with latest commit. Didn't notice it again

**Comment by mhettig** [comment]
I've also never seen that again in the last weeks.
