### ISSUE TITLE
Widget gets automatically removed when dragging it onto "app details"

### ISSUE THREAD

**Issue by SEQUOiA87** [martinhellwig/DatapassWidget#2]
**Device:** Pixel XL
**Android OS Version:** 7.1.1
**Used Launcher (since I think this is important):** Standard Pixel Launcher
**Issue:**
When I long-press an instance of the Datapass widget (no matter if it's the only instance currently on my screen), then drag and drop it onto the appearing "app details" to open the details of the Datapass app and press the device's home button afterwards, the widget is gone. 
This is not normal behavior and it's also not happening with several other native & 3 party app widgets I tested.
What's even weirder: I debugged to see which of the `AppWidgetProvider`'s methods (that's the class our `WidgetAutoUpdateProvider` extends) is called in this case, aaaand the answer is: None of them 😕 

See captured video: [device-2016-12-30-193339.mp4.zip](https://github.com/martinhellwig/DatapassWidget/files/679076/device-2016-12-30-193339.mp4.zip)

**Comment by SEQUOiA87** [comment]
Do you see this on your device, too, @mhettig?

Because it seems so weird, I hope it's a device/launcher-specific issue 😛

**Comment by mhettig** [comment]
Huawei's EMUI launcher doesn't seem to have the "app details" functionalty. I can just drag&drop the widget onto a "remove" icon.

**Comment by SEQUOiA87** [comment]
Ok, thanks for trying.

**Comment by mhettig** [comment]
In the meantime I've also tried this with Huawei's new EMUI 5.0 launcher and the Google Now Launcher. Both doesn't offer the "app details" functionality.

**Comment by SEQUOiA87** [comment]
@mhettig Really (reg. Google Now Launcher)? So there is just the "remove" possibility? I thought my last two private Motorola devices had the "app details" possibility, but maybe I confuse it with a long press on an app instead of on a widget.

**Comment by mhettig** [comment]
![screenshot_20170115-211802](https://cloud.githubusercontent.com/assets/2598617/21965839/451ea53e-db68-11e6-9b01-ccea22ac51ce.png)

**Comment by SEQUOiA87** [comment]
Ok, thanks ;)

**Comment by martinhellwig** [comment]
Cannot reproduce ;)
