### ISSUE TITLE
Font size doesn't change on resize

### ISSUE THREAD

**Issue by mhettig** [martinhellwig/DatapassWidget#3]
When increasing the size of the widget (e.g. to 2x2) the font size doesn't resize accordingly resulting in a weired look & feel.

Also with the current design it seems unncessary that the widget can be resized to non quadratic values (e.g. 4x1).

Huawei P9 - Android 6.0

**Comment by SEQUOiA87** [comment]
Yes, this is a problem on all devices. As I found out, changing the text to fit the current widget size is not trivial (and one of the reasons many developers instead provide different widgets for different grid sizes, like 1x1, 1x2, 4x4 and so on).

But as you can read on [this StackOverflow post](http://stackoverflow.com/a/40060178) (the last answer), it should be possible with this hack.

But: Keep in mind that we got a round (non-rectanglular) background image we want to fit our text to... I think this is another non-trivial problem, but hey, just another challenge for us ;)

**Comment by SEQUOiA87** [comment]
Well, you can also just remove the ability to resize the widget if you want :) I'm fine with that, too.

**Comment by mhettig** [comment]
Even if we adapt the font size it would still just look like a zoomed in version of the 1x1 one and therefore kind of weird. If we want a bigger widget I would suggest another form factor like 3x1 or 5x1 and show more information from the datapass homepage in this case, e.g. the date when the next period starts.

**Comment by SEQUOiA87** [comment]
Yes, you are right. I would suggest then to just remove the ability to resize the widget for now.

**Comment by mhettig** [comment]
Okay I'll do it.
