### ISSUE TITLE
Show "volume reached" hint if WiFi is on?

### ISSUE THREAD

**Issue by mhettig** [martinhellwig/DatapassWidget#5]
When the allowed data volume is reached the widget shows a corresponding hint. Now if you turn on WiFi this information is "lost" and the widget just shows the turn-on-mobile-data hint.

Is this a desired behavior? It might be useful for the user to know in advance if his data volume is reached before he leaves the current WiFi.

**Comment by SEQUOiA87** [comment]
Well, what I did with 071b450d24573c5243ba3024c33b509289ca636d for the Quick Settings Tile is just: 
Handle the `WASTED` return code of the `DataSupplier` just as another successful result, but just set the field `trafficWastedPercentage` to 100. 

Of course, for the App Widget you want to display more information than just the percentage, but in general I would treat this case not as an error case, so I would save the 100 percentage as you do for a `SUCCESS` return code.

**Comment by SEQUOiA87** [comment]
Tried to address this issue with 0afee4e71fdf5cfe7930de7797e742203dbee0f1.

@mhettig Please have a look and if you are satisfied, please close this issue :)

**Comment by mhettig** [comment]
That's fine with me :)
