### ISSUE TITLE
No auto reload when turn off WiFi and/or turn on mobile data

### ISSUE THREAD

**Issue by mhettig** [martinhellwig/DatapassWidget#6]
**Situation:**
User places the widget on the homescreen and mobile data is turned off.

**Current system behavior**
User gets a hint to turn on mobile data.

**Reaction (hopefully):**
User turns on mobile data.

**Problem:**
Widget still shows the turn-on-mobile-data hint -> Obscure user feedback. User might not understand why the widgets doesn't show any values although he turned on mobile data. The possibility to click the widget might not be discoverable enough in this situation.

**Possible Solution:**
Listen to wifi-off & mobile-data-on events to trigger a widget update in this case. According to several StackOverflow post there should be broadcasts for this.

**Comment by martinhellwig** [comment]
Handled with commit 98088a1
